### ISSUE TITLE
What to write in Day 3 SWE?

### ISSUE THREAD

**Issue by DeeptangshuSaha** [PixMusicaX/Sem5IOT#4]
Bhai sobtai ki likhte hbe ??

**Comment by PixMusicaX** [comment]
no no for SWE, Day3 onwards in simply print

**Comment by DeeptangshuSaha** [comment]
Okay So only Ass1 to be written else all print.

**Comment by PixMusicaX** [comment]
One and two to be exact, the codes for LMS has to be written otherwise you can write your own too!
